### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by YaibaToKen** [DemoXinMC/FortuneOres2#9]
So.. while trying to build a modpack, I've been constantly getting this crash... The crash doesn't happen if I remove this mod :( and as far as I could see from this [crash report](https://pastebin.com/r3R9qx44), the only mod "complaining" about something is yours. Apologies if I misread the log.

**Comment by DemoXinMC** [comment]
You haven't misread the log.  The issue is that some mod in your pack has an item that is returning a null for Item.getItemStackDisplayName().  My mod is erroring because I build my localization based on other mods given names (makes it SUPER simple to localize FortuneOres), and someone else is intentionally throwing bad code.

**Comment by YaibaToKen** [comment]
Any help on a way to find out the infracting mod, aside from testing them one by one?

**Comment by YaibaToKen** [comment]
As I changed the mods around again due to limitations imposed by a friend's hardware the problem is gone. I'll be closing the issue, if you need me to test around and see who the offender is, just let me know.
